openapi: 3.0.0
info:
  title: Chatbot API
  description: API for chatbot
  version: 1.0.0
paths:
  /chat:
    post:
      summary: Chat with the bot
      description: Chat with the bot
      operationId: /chat
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                edition:
                  type: object
                  properties:
                    course-id:
                      type: string
                      format: uuid
                    version:
                      type: integer
                  required:
                    - course-id
                    - version
                language:
                  type: string
                  enum:
                    - ja
                    - en
                messages:
                  type: array
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                        enum:
                          - user
                          - chatbot
                      content:
                        type: string
                    required:
                      - role
                      - content
              required:
                - edition
                - language
                - messages
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
  /create-course:
    post:
      summary: Creates a new course
      description: Creates a new course
      operationId: /create-course
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                customer:
                  type: object
                  properties:
                    name:
                      type: object
                      properties:
                        firstName:
                          type: string
                        lastName:
                          type: string
                      required:
                        - firstName
                        - lastName
                    age:
                      type: integer
                    gender:
                      type: string
                      enum:
                        - female
                        - male
                    personality:
                      type: string
                    industry:
                      type: string
                    position:
                      type: string
                    department:
                      type: string
                    companyName:
                      type: string
                  required:
                    - name
                    - age
                    - gender
                    - personality
                    - industry
                    - position
                    - department
                    - companyName
                conversation:
                  type: object
                  properties:
                    background:
                      type: string
                    objective:
                      type: string
                    proposal:
                      type: string
                    plan:
                      type: string
                  required:
                    - background
                    - objective
                    - proposal
                    - plan
                evaluationCriteria:
                  type: array
                  items:
                    type: string
                  minItems: 1
              required:
                - title
                - description
                - customer
                - conversation
                - evaluationCriteria
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  courseId:
                    type: string
                    format: uuid
                required:
                  - courseId
  /evaluate:
    post:
      summary: Evaluate a conversation
      description: Evaluate a conversation
      operationId: /evaluate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                language:
                  type: string
                  enum:
                    - ja
                    - en
                edition:
                  type: object
                  properties:
                    courseId:
                      type: string
                      format: uuid
                    editionVersion:
                      type: integer
                  required:
                    - courseId
                    - editionVersion
                transcription:
                  type: array
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                        enum:
                          - user
                          - chatbot
                      content:
                        type: string
                    required:
                      - role
                      - content
              required:
                - language
                - edition
                - transcription
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment:
                    type: string
                  perCriterion:
                    type: array
                    items:
                      type: object
                      properties:
                        criterion:
                          type: string
                        score:
                          type: integer
                        comment:
                          type: string
                      required:
                        - criterion
                        - score
                        - comment
                required:
                  - comment
                  - perCriterion
  /list-courses:
    post:
      summary: List all the courses
      description: List all the courses
      operationId: /list-courses
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    latestEditionVersion:
                      type: integer
                    title:
                      type: string
                  required:
                    - id
                    - latestEditionVersion
                    - title
  /remove-all-courses:
    post:
      summary: Remove all courses
      description: Remove all courses
      operationId: /remove-all-courses
      responses:
        "200":
          description: Success
  /remove-course:
    post:
      summary: Remove a course
      description: Remove a course
      operationId: /remove-course
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
              required:
                - id
      responses:
        "200":
          description: Success
  /retrieve-simulation-evaluation:
    post:
      summary: Get the evaluation of a course simulation
      description: Get the evaluation of a course simulation
      operationId: /retrieve-simulation-evaluation
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  summaryCards:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        description:
                          type: string
                        fact:
                          type: string
                        mdiIcon:
                          type: string
                        rating:
                          type: object
                          properties:
                            label:
                              type: string
                            color:
                              type: string
                          required:
                            - label
                            - color
                      required:
                        - title
                        - description
                        - fact
                        - mdiIcon
                        - rating
                  scoreCards:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        criteria:
                          type: array
                          items:
                            type: object
                            properties:
                              title:
                                type: string
                              description:
                                type: string
                              fulfilled:
                                type: boolean
                            required:
                              - title
                              - description
                              - fulfilled
                      required:
                        - title
                        - criteria
                required:
                  - summaryCards
                  - scoreCards
  /stt:
    post:
      summary: Speech to text
      description: Speech to text
      operationId: /stt
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                language:
                  type: string
                  enum:
                    - ja
                    - en
                audio:
                  type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: number
                    sampleRate:
                      type: integer
                  required:
                    - data
                    - sampleRate
              required:
                - language
                - audio
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
  /tts:
    post:
      summary: Text to speech
      description: Text to speech
      operationId: /tts
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
                - text
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: binary
